// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119231837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Server.Models.DbActiveInvestment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("ActiveInvestments");
                });

            modelBuilder.Entity("Server.Models.DbInvestmentOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequiredAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvestmentOptions");

                    b.HasData(
                        new
                        {
                            Id = "short",
                            DurationSeconds = 10,
                            ExpectedReturn = 20m,
                            Name = "Short-term investment",
                            RequiredAmount = 10m
                        },
                        new
                        {
                            Id = "mid",
                            DurationSeconds = 30,
                            ExpectedReturn = 250m,
                            Name = "Mid-term investment",
                            RequiredAmount = 100m
                        },
                        new
                        {
                            Id = "long",
                            DurationSeconds = 60,
                            ExpectedReturn = 3000m,
                            Name = "Long-term investment",
                            RequiredAmount = 1000m
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Models.DbActiveInvestment", b =>
                {
                    b.HasOne("Server.Models.User", "User")
                        .WithMany("ActiveInvestments")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("ActiveInvestments");
                });
#pragma warning restore 612, 618
        }
    }
}
