// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120192907_SeedInvestmentOptions")]
    partial class SeedInvestmentOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Server.Models.DbActiveInvestment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("ActiveInvestments");
                });

            modelBuilder.Entity("Server.Models.DbInvestmentOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedReturn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequiredAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvestmentOptions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            DurationSeconds = 30,
                            ExpectedReturn = 525m,
                            Name = "Short-term Bond",
                            RequiredAmount = 500m
                        },
                        new
                        {
                            Id = "2",
                            DurationSeconds = 60,
                            ExpectedReturn = 1680m,
                            Name = "Tech Stock Bundle",
                            RequiredAmount = 1500m
                        },
                        new
                        {
                            Id = "3",
                            DurationSeconds = 120,
                            ExpectedReturn = 6250m,
                            Name = "Venture Capital",
                            RequiredAmount = 5000m
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastBalanceUpdate")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Models.DbActiveInvestment", b =>
                {
                    b.HasOne("Server.Models.User", "User")
                        .WithMany("ActiveInvestments")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("ActiveInvestments");
                });
#pragma warning restore 612, 618
        }
    }
}
